development:
  sEDMINE_DB_PASSWORD: supersecretkey
  REDMINE_DB_PASSWORD: testpassword
  


production:
  EDMINE_DB_PASSWORD: <%= ENV["SECRET_KEY_BASE"] %>
  REDMINE_DB_PASSWORD: <%= ENV["EDMINE_DB_PASSWORD"] %>